name: Backend CD - Deploy to Render

on:
  schedule:
    # TODOS LOS VIERNES A LAS 15:00 HORA COLOMBIA ( 20:00 UTC )
    - cron: "0 20 * * 5"

  # PERMIRIR DESPLEGAR MANUALMENTE
  workflow_dispatch:

jobs:
  Deploy-Render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v1.1.0/cli_1.1.0_linux_amd64.zip -o render.zip
          unzip render.zip
          sudo mv cli_v1.1.0 /usr/local/bin/render

      - name: Trigger deploy with Render CLI
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          CI: true
        run: |
          render deploys create ${{ secrets.RENDER_PRODUCTS_SERVICE_ID }} --output json --confirm
